[tox]
isolated_build = true
envlist =
    py311
    pre-commit

[testenv]
allowlist_externals = poetry
passenv =
    AIRTABLE_API_KEY
setenv =
    AIRTABLE_CACHE_DIR = {envtmpdir}/cache
    VCR_RECORD_MODE = {env:VCR_RECORD_MODE:none}

[testenv:pre-commit]
deps = pre-commit
commands =
    pre-commit install --install-hooks
    pre-commit run --all-files

[testenv:py311]
testpaths = tests
commands_pre =
    poetry sync --no-root
commands =
    poetry run mypy --strict -p airtable_proxy
    poetry run python -m pytest -vv {posargs}

[testenv:coverage]
commands_pre =
    poetry sync --no-root
commands =
    poetry run python -m pytest -x -vv \
        --cov=airtable_proxy \
        --cov-report=term-missing \
        --cov-fail-under=100

[flake8]
filename = *.py
count = True
# See https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
ignore = E203, E231, E266, E501, W503
select = B,C,E,F,W,T4,B9
max-line-length = 88
max-complexity = 15
exclude =
    .venv
    .eggs
    .tox
    ./docs
